export default interface CareerInformationHttpUpdateRequest {
  personCareerInformationId: string;
  companyName: string | null;
  updateCompanyName: boolean;
  companyWebsite: string | null;
  updateCompanyWebsite: boolean;
  jobTitle: string | null;
  updateJobTitle: boolean;
  position: string | null;
  updatePosition: boolean;
  cityOfEmployment: string | null;
  updateCityOfEmployment: boolean;
  countryOfEmployment: string | null;
  updateCountryOfEmployment: boolean;
  employmentTypeId: number | null;
  updateEmploymentTypeId: boolean;
  startDate: string | null;
  updateStartDate: boolean;
  endDate: string | null;
  updateEndDate: boolean;
  jobDescription: string | null;
  updateJobDescription: boolean;
  responsibilities: string | null;
  updateResponsibilities: boolean;
  achievements: string | null;
  updateAchievements: boolean;
  industryClassificationId: string | null;
  updateIndustryClassificationId: boolean;
  skillsUsed: string | null;
  updateSkillsUsed: boolean;
  workTypeId: number | null;
  updateWorkTypeId: boolean;
  additionalInformation: string | null;
  updateAdditionalInformation: boolean;
}
